services:
  9mm:
    build:
      context: .
    ports:
      - "8013:8013"
    env_file:
      - .env
    depends_on:
      - redis-9mm

  redis-9mm:
    image: redis:latest
    ports:
      - "6387:6379"


